[book]
authors = ["sevki"]
language = "en"
multilingual = false
src = "docs"
title = "okLinux"

# additional css https://raw.githubusercontent.com/oknotokcomputer/okcss/main/ok.css
[output.html]
additional-css = ["ok.css"]
theme = "theme"